spring:
  datasource:
    url: jdbc:h2:mem://localhost/~/testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

jpa:
  hibernate:
    ddl-auto: create-drop
  properties:
    hibrtnate:
      format_sql: true